// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ddqaynfhwfcqaptbxjbg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRkcWF5bmZod2ZjcWFwdGJ4amJnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2MTYwMTksImV4cCI6MjA3NDE5MjAxOX0.k611sZKP2KgO9IuDnnz0tN9TPlQjrnsrXDvPmY-gApg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});